name: tray_manager
description: This plugin allows Flutter desktop apps to defines system tray.
version: 0.2.0
homepage: https://github.com/leanflutter/tray_manager

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  menu_base: ^0.1.1
  path: ^1.9.1
  shortid: ^0.1.2

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: TrayManagerPlugin
      macos:
        pluginClass: TrayManagerPlugin
      windows:
        pluginClass: TrayManagerPlugin
